package DistributedTest.patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = 'DistributedGradle_Check' (id = 'DistributedTest')
accordingly, and delete the patch script.
*/
changeProject(uuid("DistributedGradle_Check")) {
    params {
        add {
            param("gradle.cache.remote.url", "credentialsJSON:e5dbdfce-68c9-4022-a084-155bd822e791")
        }
    }
}
